# import libraries that we need
from AhpAnpLib import inputs_AHPLib as input
from AhpAnpLib import structs_AHPLib as str
from AhpAnpLib import calcs_AHPLib as calc

# create the model
Shoesmodel=str.Model("Athletic Shoes model")

Alternatives=str.Cluster("1. Alternatives",0)
A1=str.Node("Adidas",0)
Alternatives.addNode2Cluster(A1)
A2=str.Node("Nike",1)
Alternatives.addNode2Cluster(A2)
A3=str.Node("Reebok",2)
Alternatives.addNode2Cluster(A3)
Shoesmodel.addCluster2Model(Alternatives)

Advertising=str.Cluster("2. Advertising",1)
brand=str.Node("Brand Image",3)
creativity=str.Node("Creativity",4)
frequncy=str.Node("Frequency",5)
printAd=str.Node("Print Ad.",6)
television=str.Node("Television",7)
Advertising.addMultipleNodes2Cluster(brand,creativity,frequncy,printAd,television)
Shoesmodel.addCluster2Model(Advertising)

cl2=str.Cluster("3. Product Characteristics",2)
nd2=str.Node("Comfort",8)
cl2.addNode2Cluster(nd2)
nd2=str.Node("Innovation",9)
cl2.addNode2Cluster(nd2)
nd2=str.Node("Product Line",10)
cl2.addNode2Cluster(nd2)
nd2=str.Node("Quality",11)
cl2.addNode2Cluster(nd2)
nd2=str.Node("Style",12)
cl2.addNode2Cluster(nd2)
new_model.addCluster2Model(cl2)

cl3=str.Cluster("4. Customers",3)
nd3=str.Node("Others",13)
cl3.addNode2Cluster(nd3)
nd3=str.Node("Professional athletes",14)
cl3.addNode2Cluster(nd3)
nd3=str.Node("Students",15)
cl3.addNode2Cluster(nd3)
nd3=str.Node("Teenagers",16)
cl3.addNode2Cluster(nd3)
nd3=str.Node("Urban male",17)
cl3.addNode2Cluster(nd3)
new_model.addCluster2Model(cl3)

new_model.addNodeConnectionFromTo("Adidas","Frequency",False)
new_model.addNodeConnectionFromTo("Adidas","Creativity",False)
new_model.addNodeConnectionFromTo("Adidas","Television",False)
new_model.addNodeConnectionFromTo("Adidas","Print Ad.",False)
new_model.addNodeConnectionFromTo("Adidas","Brand Image",False)
new_model.addNodeConnectionFromTo("Nike","Frequency",False)
new_model.addNodeConnectionFromTo("Nike","Creativity",False)
new_model.addNodeConnectionFromTo("Nike","Television",False)
new_model.addNodeConnectionFromTo("Nike","Print Ad.",False)
new_model.addNodeConnectionFromTo("Nike","Brand Image",False)
new_model.addNodeConnectionFromTo("Reebok","Frequency",False)
new_model.addNodeConnectionFromTo("Reebok","Creativity",False)
new_model.addNodeConnectionFromTo("Reebok","Television",False)
new_model.addNodeConnectionFromTo("Reebok","Print Ad.",False)
new_model.addNodeConnectionFromTo("Reebok","Brand Image",False)
new_model.addNodeConnectionFromTo("Adidas","Product Line",False)
new_model.addNodeConnectionFromTo("Adidas","Innovation",False)
new_model.addNodeConnectionFromTo("Adidas","Quality",False)
new_model.addNodeConnectionFromTo("Adidas","Comfort",False)
new_model.addNodeConnectionFromTo("Adidas","Style",False)
new_model.addNodeConnectionFromTo("Nike","Style",False)
new_model.addNodeConnectionFromTo("Nike","Comfort",False)
new_model.addNodeConnectionFromTo("Nike","Quality",False)
new_model.addNodeConnectionFromTo("Nike","Innovation",False)
new_model.addNodeConnectionFromTo("Nike","Product Line",False)
new_model.addNodeConnectionFromTo("Reebok","Style",False)
new_model.addNodeConnectionFromTo("Reebok","Comfort",False)
new_model.addNodeConnectionFromTo("Reebok","Quality",False)
new_model.addNodeConnectionFromTo("Reebok","Innovation",False)
new_model.addNodeConnectionFromTo("Reebok","Product Line",False)
new_model.addNodeConnectionFromTo("Adidas","Students",False)
new_model.addNodeConnectionFromTo("Adidas","Urban male",False)
new_model.addNodeConnectionFromTo("Adidas","Professional athletes",False)
new_model.addNodeConnectionFromTo("Adidas","Teenagers",False)
new_model.addNodeConnectionFromTo("Adidas","Others",False)
new_model.addNodeConnectionFromTo("Nike","Professional athletes",False)
new_model.addNodeConnectionFromTo("Nike","Students",False)
new_model.addNodeConnectionFromTo("Nike","Urban male",False)
new_model.addNodeConnectionFromTo("Nike","Teenagers",False)
new_model.addNodeConnectionFromTo("Nike","Others",False)
new_model.addNodeConnectionFromTo("Reebok","Teenagers",False)
new_model.addNodeConnectionFromTo("Reebok","Urban male",False)
new_model.addNodeConnectionFromTo("Reebok","Students",False)
new_model.addNodeConnectionFromTo("Reebok","Professional athletes",False)
new_model.addNodeConnectionFromTo("Reebok","Others",False)
new_model.addNodeConnectionFromTo("Brand Image","Nike",False)
new_model.addNodeConnectionFromTo("Brand Image","Reebok",False)
new_model.addNodeConnectionFromTo("Brand Image","Adidas",False)
new_model.addNodeConnectionFromTo("Creativity","Nike",False)
new_model.addNodeConnectionFromTo("Creativity","Reebok",False)
new_model.addNodeConnectionFromTo("Creativity","Adidas",False)
new_model.addNodeConnectionFromTo("Frequency","Nike",False)
new_model.addNodeConnectionFromTo("Frequency","Reebok",False)
new_model.addNodeConnectionFromTo("Frequency","Adidas",False)
new_model.addNodeConnectionFromTo("Print Ad.","Nike",False)
new_model.addNodeConnectionFromTo("Print Ad.","Reebok",False)
new_model.addNodeConnectionFromTo("Print Ad.","Adidas",False)
new_model.addNodeConnectionFromTo("Television","Nike",False)
new_model.addNodeConnectionFromTo("Television","Reebok",False)
new_model.addNodeConnectionFromTo("Television","Adidas",False)
new_model.addNodeConnectionFromTo("Creativity","Television",False)
new_model.addNodeConnectionFromTo("Creativity","Print Ad.",False)
new_model.addNodeConnectionFromTo("Frequency","Television",False)
new_model.addNodeConnectionFromTo("Frequency","Print Ad.",False)
new_model.addNodeConnectionFromTo("Print Ad.","Creativity",False)
new_model.addNodeConnectionFromTo("Print Ad.","Frequency",False)
new_model.addNodeConnectionFromTo("Television","Creativity",False)
new_model.addNodeConnectionFromTo("Television","Frequency",False)
new_model.addNodeConnectionFromTo("Creativity","Style",False)
new_model.addNodeConnectionFromTo("Creativity","Product Line",False)
new_model.addNodeConnectionFromTo("Creativity","Comfort",False)
new_model.addNodeConnectionFromTo("Creativity","Quality",False)
new_model.addNodeConnectionFromTo("Creativity","Innovation",False)
new_model.addNodeConnectionFromTo("Print Ad.","Style",False)
new_model.addNodeConnectionFromTo("Print Ad.","Comfort",False)
new_model.addNodeConnectionFromTo("Print Ad.","Quality",False)
new_model.addNodeConnectionFromTo("Print Ad.","Innovation",False)
new_model.addNodeConnectionFromTo("Print Ad.","Product Line",False)
new_model.addNodeConnectionFromTo("Television","Style",False)
new_model.addNodeConnectionFromTo("Television","Comfort",False)
new_model.addNodeConnectionFromTo("Television","Quality",False)
new_model.addNodeConnectionFromTo("Television","Innovation",False)
new_model.addNodeConnectionFromTo("Television","Product Line",False)
new_model.addNodeConnectionFromTo("Brand Image","Professional athletes",False)
new_model.addNodeConnectionFromTo("Brand Image","Students",False)
new_model.addNodeConnectionFromTo("Brand Image","Urban male",False)
new_model.addNodeConnectionFromTo("Brand Image","Teenagers",False)
new_model.addNodeConnectionFromTo("Brand Image","Others",False)
new_model.addNodeConnectionFromTo("Creativity","Professional athletes",False)
new_model.addNodeConnectionFromTo("Creativity","Students",False)
new_model.addNodeConnectionFromTo("Creativity","Urban male",False)
new_model.addNodeConnectionFromTo("Creativity","Teenagers",False)
new_model.addNodeConnectionFromTo("Creativity","Others",False)
new_model.addNodeConnectionFromTo("Frequency","Professional athletes",False)
new_model.addNodeConnectionFromTo("Frequency","Students",False)
new_model.addNodeConnectionFromTo("Frequency","Urban male",False)
new_model.addNodeConnectionFromTo("Frequency","Teenagers",False)
new_model.addNodeConnectionFromTo("Frequency","Others",False)
new_model.addNodeConnectionFromTo("Print Ad.","Teenagers",False)
new_model.addNodeConnectionFromTo("Print Ad.","Urban male",False)
new_model.addNodeConnectionFromTo("Print Ad.","Students",False)
new_model.addNodeConnectionFromTo("Print Ad.","Professional athletes",False)
new_model.addNodeConnectionFromTo("Print Ad.","Others",False)
new_model.addNodeConnectionFromTo("Television","Professional athletes",False)
new_model.addNodeConnectionFromTo("Television","Students",False)
new_model.addNodeConnectionFromTo("Television","Urban male",False)
new_model.addNodeConnectionFromTo("Television","Teenagers",False)
new_model.addNodeConnectionFromTo("Television","Others",False)
new_model.addNodeConnectionFromTo("Comfort","Nike",False)
new_model.addNodeConnectionFromTo("Comfort","Reebok",False)
new_model.addNodeConnectionFromTo("Comfort","Adidas",False)
new_model.addNodeConnectionFromTo("Innovation","Nike",False)
new_model.addNodeConnectionFromTo("Innovation","Reebok",False)
new_model.addNodeConnectionFromTo("Innovation","Adidas",False)
new_model.addNodeConnectionFromTo("Product Line","Nike",False)
new_model.addNodeConnectionFromTo("Product Line","Reebok",False)
new_model.addNodeConnectionFromTo("Product Line","Adidas",False)
new_model.addNodeConnectionFromTo("Quality","Nike",False)
new_model.addNodeConnectionFromTo("Quality","Reebok",False)
new_model.addNodeConnectionFromTo("Quality","Adidas",False)
new_model.addNodeConnectionFromTo("Style","Nike",False)
new_model.addNodeConnectionFromTo("Style","Reebok",False)
new_model.addNodeConnectionFromTo("Style","Adidas",False)
new_model.addNodeConnectionFromTo("Comfort","Professional athletes",False)
new_model.addNodeConnectionFromTo("Comfort","Students",False)
new_model.addNodeConnectionFromTo("Comfort","Urban male",False)
new_model.addNodeConnectionFromTo("Comfort","Teenagers",False)
new_model.addNodeConnectionFromTo("Comfort","Others",False)
new_model.addNodeConnectionFromTo("Innovation","Professional athletes",False)
new_model.addNodeConnectionFromTo("Innovation","Students",False)
new_model.addNodeConnectionFromTo("Innovation","Urban male",False)
new_model.addNodeConnectionFromTo("Innovation","Teenagers",False)
new_model.addNodeConnectionFromTo("Innovation","Others",False)
new_model.addNodeConnectionFromTo("Product Line","Professional athletes",False)
new_model.addNodeConnectionFromTo("Product Line","Students",False)
new_model.addNodeConnectionFromTo("Product Line","Urban male",False)
new_model.addNodeConnectionFromTo("Product Line","Teenagers",False)
new_model.addNodeConnectionFromTo("Product Line","Others",False)
new_model.addNodeConnectionFromTo("Quality","Professional athletes",False)
new_model.addNodeConnectionFromTo("Quality","Students",False)
new_model.addNodeConnectionFromTo("Quality","Urban male",False)
new_model.addNodeConnectionFromTo("Quality","Teenagers",False)
new_model.addNodeConnectionFromTo("Quality","Others",False)
new_model.addNodeConnectionFromTo("Style","Professional athletes",False)
new_model.addNodeConnectionFromTo("Style","Students",False)
new_model.addNodeConnectionFromTo("Style","Urban male",False)
new_model.addNodeConnectionFromTo("Style","Teenagers",False)
new_model.addNodeConnectionFromTo("Style","Others",False)
new_model.addNodeConnectionFromTo("Others","Nike",False)
new_model.addNodeConnectionFromTo("Others","Reebok",False)
new_model.addNodeConnectionFromTo("Others","Adidas",False)
new_model.addNodeConnectionFromTo("Professional athletes","Nike",False)
new_model.addNodeConnectionFromTo("Professional athletes","Reebok",False)
new_model.addNodeConnectionFromTo("Professional athletes","Adidas",False)
new_model.addNodeConnectionFromTo("Students","Nike",False)
new_model.addNodeConnectionFromTo("Students","Reebok",False)
new_model.addNodeConnectionFromTo("Students","Adidas",False)
new_model.addNodeConnectionFromTo("Teenagers","Nike",False)
new_model.addNodeConnectionFromTo("Teenagers","Reebok",False)
new_model.addNodeConnectionFromTo("Teenagers","Adidas",False)
new_model.addNodeConnectionFromTo("Urban male","Nike",False)
new_model.addNodeConnectionFromTo("Urban male","Reebok",False)
new_model.addNodeConnectionFromTo("Urban male","Adidas",False)
new_model.addNodeConnectionFromTo("Others","Print Ad.",False)
new_model.addNodeConnectionFromTo("Others","Television",False)
new_model.addNodeConnectionFromTo("Others","Creativity",False)
new_model.addNodeConnectionFromTo("Others","Frequency",False)
new_model.addNodeConnectionFromTo("Others","Brand Image",False)
new_model.addNodeConnectionFromTo("Professional athletes","Television",False)
new_model.addNodeConnectionFromTo("Professional athletes","Print Ad.",False)
new_model.addNodeConnectionFromTo("Professional athletes","Creativity",False)
new_model.addNodeConnectionFromTo("Professional athletes","Frequency",False)
new_model.addNodeConnectionFromTo("Professional athletes","Brand Image",False)
new_model.addNodeConnectionFromTo("Students","Frequency",False)
new_model.addNodeConnectionFromTo("Students","Creativity",False)
new_model.addNodeConnectionFromTo("Students","Television",False)
new_model.addNodeConnectionFromTo("Students","Print Ad.",False)
new_model.addNodeConnectionFromTo("Students","Brand Image",False)
new_model.addNodeConnectionFromTo("Teenagers","Print Ad.",False)
new_model.addNodeConnectionFromTo("Teenagers","Television",False)
new_model.addNodeConnectionFromTo("Teenagers","Creativity",False)
new_model.addNodeConnectionFromTo("Teenagers","Frequency",False)
new_model.addNodeConnectionFromTo("Teenagers","Brand Image",False)
new_model.addNodeConnectionFromTo("Urban male","Frequency",False)
new_model.addNodeConnectionFromTo("Urban male","Creativity",False)
new_model.addNodeConnectionFromTo("Urban male","Television",False)
new_model.addNodeConnectionFromTo("Urban male","Print Ad.",False)
new_model.addNodeConnectionFromTo("Urban male","Brand Image",False)
new_model.addNodeConnectionFromTo("Others","Style",False)
new_model.addNodeConnectionFromTo("Others","Comfort",False)
new_model.addNodeConnectionFromTo("Others","Quality",False)
new_model.addNodeConnectionFromTo("Others","Innovation",False)
new_model.addNodeConnectionFromTo("Others","Product Line",False)
new_model.addNodeConnectionFromTo("Professional athletes","Quality",False)
new_model.addNodeConnectionFromTo("Professional athletes","Innovation",False)
new_model.addNodeConnectionFromTo("Professional athletes","Comfort",False)
new_model.addNodeConnectionFromTo("Professional athletes","Style",False)
new_model.addNodeConnectionFromTo("Students","Style",False)
new_model.addNodeConnectionFromTo("Students","Comfort",False)
new_model.addNodeConnectionFromTo("Students","Quality",False)
new_model.addNodeConnectionFromTo("Students","Innovation",False)
new_model.addNodeConnectionFromTo("Teenagers","Style",False)
new_model.addNodeConnectionFromTo("Teenagers","Comfort",False)
new_model.addNodeConnectionFromTo("Teenagers","Quality",False)
new_model.addNodeConnectionFromTo("Teenagers","Innovation",False)
new_model.addNodeConnectionFromTo("Teenagers","Product Line",False)
new_model.addNodeConnectionFromTo("Urban male","Style",False)
new_model.addNodeConnectionFromTo("Urban male","Quality",False)
new_model.addNodeConnectionFromTo("Urban male","Innovation",False)
new_model.printStruct()
new_model.drawGraphClusters()
new_model.drawGraphNodes()
input.export4ExcelQuestFull(new_model,"py_file_Athletic Shoes model_empty.xlsx",verb=False)
calc.calcAHPMatricesSave2File(new_model,"Athletic Shoes model_filledIn.xlsx","py_file_Athletic Shoes model_results.xlsx",inputFileUse=True,normalbar=False,idealbar=True,verbal=False)
calc.copyExcelSheet("py_file_Athletic Shoes model_results.xlsx","py_file_Athletic Shoes model_filledIn.xlsx", "pairwise_comp",False)